# Generated by Django 4.0.4 on 2022-05-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_rename_usermessage_usermessages_remove_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cardnumber',
            field=models.CharField(max_length=19, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cvc',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
