# Generated by Django 4.0.4 on 2022-05-06 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_usermessages_from_user_alter_usermessages_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessages',
            old_name='from_user',
            new_name='to_user',
        ),
    ]
