# Generated by Django 4.0.4 on 2022-05-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_messagingapp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessagingApp',
            new_name='Chait_messages',
        ),
    ]
