# Generated by Django 4.0.4 on 2022-05-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_rename_messagingapp_chait_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chait_messages',
            new_name='Chat_messages',
        ),
        migrations.RenameField(
            model_name='chat_messages',
            old_name='user_chait',
            new_name='user_chat',
        ),
    ]
