# Generated by Django 4.0.4 on 2022-05-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_remove_user_profile_pic_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='profile_pic',
            field=models.ImageField(upload_to='media/pic'),
        ),
    ]
