# Generated by Django 4.0.4 on 2022-05-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_alter_profilepic_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='profile_pic',
            field=models.ImageField(upload_to='media'),
        ),
    ]
