# Generated by Django 4.0.4 on 2022-06-02 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0017_alter_profilepic_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='on_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
