# Generated by Django 4.0.4 on 2022-06-03 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0018_blogpost_on_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='on_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='user_blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_blog_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
