# Generated by Django 4.0.4 on 2022-06-13 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0019_alter_blogpost_on_time_alter_blogpost_user_blog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepic',
            old_name='profile_pic',
            new_name='pic',
        ),
    ]
