# Generated by Django 4.0.4 on 2022-06-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0020_rename_profile_pic_profilepic_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
