# Generated by Django 4.0.4 on 2023-06-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0024_alter_student_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='School',
            new_name='school',
        ),
    ]
